### ISSUE TITLE
Dependencies Security Vulnerabilities

### ISSUE THREAD

**Issue by michal-ayash** [devrafalko/webpack-karma-jasmine#5]
This package requires an old version of 'karma' (3.1.4) that requires 'set-value' with old version (2.0.0) which has vulnerability issue.
Updating the package to require the latest version of karma (4.2.0) will resolve the issue.

Thanks,
Michal.

**Comment by devrafalko** [comment]
Ok, try new version `npm install webpack-karma-jasmine@3.0.7`
