### ISSUE TITLE
Dependency Security Violation

### ISSUE THREAD

**Issue by clh15683** [devrafalko/webpack-karma-jasmine#7]
Hi,

webpack-karma-jasmine depends on karma 4.2.0, which causes minimist 0.0.10 to be loaded. The chain is:
karma 4.2.0 -> optimist 0.6.1 -> minimist 0.0.10
This reports a security violation https://npmjs.com/advisories/1179  .
This is fixed in karma >= 5.0.0, which no longer depends on optimist. Is it possible to upgrade to karma 5.0.0?

Thanks

**Comment by devrafalko** [comment]
ok, the new webpack-karma-jasmine@4.0.0 version has been published with the dependencies updated.
